const FLYER = {
    OPEN_FLYER_PANE:"OPEN_FLYER_PANE",
    SET_FLYER_MADE:"SET_FLYER_MADE",
    SET_MAKING_FLYER:"SET_MAKING_FLYER",
    SET_MAKING_FLYER_SUCCESS:"SET_MAKING_FLYER_SUCCESS",
    SET_MAKING_FLYER_FAIL:"SET_MAKING_FLYER_FAIL",
    SET_FLYERS:"SET_FLYERS",
    SET_FLYERS_SUCCESS:"SET_FLYERS_SUCCESS",
    SET_FLYERS_FAIL:"SET_FLYERS_FAIL",
    SET_SELECTED_FLYER: "SET_SELECTED_FLYER",
    SET_WISH_TO_DELETE_FLYER: "SET_WISH_TO_DELETE_FLYER",
    SET_DELETING_FLYER:"SET_DELETING_FLYER",
    SET_DELETED_FLYER:"SET_DELETED_FLYER",
    SET_DELETING_FLYER_SUCCESS:"SET_DELETING_FLYER_SUCCESS",
    SET_DELETING_FLYER_FAIL:"SET_DELETING_FLYER_FAIL"
}

export default FLYER;