const LOCATION = {
    SET_IP_LOCATION:"SET_IP_LOCATION",
    SET_VALID_PLACE: "SET_VALID_PLACE",
    SET_SELECTED_PLACE: "SET_SELECTED_PLACE",
    GET_PLACES: "GET_PLACES",
    GET_PLACES_SUCCESS: "GET_PLACES_SUCCESS",
    GET_PLACES_ERROR: "GET_PLACES_ERROR",
    INITIAL_MAP_SHOW: "INITIAL_MAP_SHOW"
}

export default LOCATION;